name: Release Automation

on:
  create:
    tags:
      - 'v*' # Trigger only when a version tag is created (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Generate Changelog
        id: changelog
        run: |
          echo "Generating changelog..."
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" > changelog.md
          cat changelog.md
        outputs:
          changelog: ${{ steps.changelog.outputs.changelog }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/